name: tcp
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0  
  cloud_functions: ^5.1.0
  cloud_firestore: ^5.4.0  
  firebase_storage: ^12.2.0
  # Autenticación y otras integraciones
  google_sign_in: ^6.2.1
  provider: ^6.0.2
  # Geolocalización y mapas
  geolocator: ^12.0.0
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  flutter_map_location_marker: ^9.0.0
  flutter_compass: ^0.8.0
  google_maps_flutter: ^2.6.1
  flutter_polyline_points: ^2.0.0
  location: ^7.0.0
  geocoding: ^3.0.0
  # Permisos
  permission_handler: ^11.3.1
  # UI y Navegación
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.6
  panara_dialogs: ^0.1.5  
  url_launcher: ^6.2.6
  flutter_toggle_tab: ^1.4.1
  material_floating_search_bar: ^0.3.7
  loading_indicator: ^3.1.1
  flutter_snake_navigationbar: ^0.6.1
  badges: ^3.1.2
  smooth_page_indicator: ^1.1.0
  flutter_markdown: ^0.7.3
  # Conectividad y sensores
  connectivity_plus: ^6.0.5
  sensors_plus: ^6.0.1
  # Otros
  http: ^1.2.1
  file_picker: ^8.0.3
  skeletonizer: ^1.3.0
  xml: any
  # Cambiar nombre de paquete
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/src/img/autenticacion.png
    - lib/src/img/email.png
    - lib/src/img/registro.png
    - lib/src/img/imfine.png
    - lib/src/img/authentication.png
    - lib/src/img/perfil.png
    - lib/src/img/registration.png
    - lib/src/kml/Rut_AlarconSabalo.kml
    - lib/src/kml/Rut_Hogar del pescador.kml
    - lib/src/kml/Rut_PradosSol.kml
