// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBn1lVH0pNAtJVUvGi7AaMAgGuz8kQQaY',
    appId: '1:139448852747:web:4ea1879fbce0e555ba820e',
    messagingSenderId: '139448852747',
    projectId: 'tcp-maps-a13a3',
    authDomain: 'tcp-maps-a13a3.firebaseapp.com',
    storageBucket: 'tcp-maps-a13a3.appspot.com',
    measurementId: 'G-Q0YFGW89QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3eom1vPnYYdzRBzy062PqbTqvHkoMN8Y',
    appId: '1:139448852747:android:6268a16437efa662ba820e',
    messagingSenderId: '139448852747',
    projectId: 'tcp-maps-a13a3',
    storageBucket: 'tcp-maps-a13a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8SJcFpg4_fBmD8BMaoAEx0bTpZlUBIFc',
    appId: '1:139448852747:ios:f8b8224c5461ca4eba820e',
    messagingSenderId: '139448852747',
    projectId: 'tcp-maps-a13a3',
    storageBucket: 'tcp-maps-a13a3.appspot.com',
    androidClientId: '139448852747-6o48fiq1peaiqmo4okulo451fhpgb4ad.apps.googleusercontent.com',
    iosBundleId: 'cam.tcp.cc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBn1lVH0pNAtJVUvGi7AaMAgGuz8kQQaY',
    appId: '1:139448852747:web:4f8d5efdad762a8fba820e',
    messagingSenderId: '139448852747',
    projectId: 'tcp-maps-a13a3',
    authDomain: 'tcp-maps-a13a3.firebaseapp.com',
    storageBucket: 'tcp-maps-a13a3.appspot.com',
    measurementId: 'G-7KVC96BTM3',
  );
}
